TokenVerifier: execute blocking calls in parallel...
knative-extensions/eventing-kafka-broker pull request #3728
Opened 2024-03-01 13:52 UTC by parth721

Fixes #3673 

Here the executeBlocking() in Vert.x framework doing serial operation, on the jwt token for authorization. Due to which as jwt token took longer to process, So I turned the default value ordered parameter to false. So, that the verification process can be done asynchronously with different verticles.

2024-03-01 14:02 UTC, parth721 commented
/cc @creydr

2024-03-01 15:07 UTC, creydr requested changes

2024-03-01 15:07 UTC, creydr commented on control-plane/pkg/contract/contract.pb.go
I think changes on this file are not needed for this change

2024-03-01 15:07 UTC, creydr commented
/ok-to-test

2024-03-01 16:39 UTC, parth721 commented
/retest-required

2024-03-03 18:21 UTC, parth721 commented on control-plane/pkg/contract/contract.pb.go
@creydr It's automatically updated, removed the changes as suggested :)

2024-03-04 08:18 UTC, merged

2024-03-04 17:09 UTC, parth721 commented
> Thanks a lot @parth721 for fixing this 👍

Thank you @creydr for your support  :)