used new logging package in all e2e test main functions
knative-extensions/eventing-kafka-broker pull request #3755
Opened 2024-03-12 16:20 UTC by NeerajNagure

Fixes #3753 

## Proposed Changes
Added the use of new logging package in e2e,e2e_source,e2e_sink,e2e_new_channel,e2e_channel main files and also removed the previous log exporter testlib wherever used in these files
:sparkles:  Used new log package

2024-03-12 17:35 UTC, Cali0707 commented on test/e2e_channel/main_test.go
> +var global environment.GlobalEnvironment
Same as above

2024-03-12 17:35 UTC, Cali0707 commented on test/e2e_sink/main_test.go
> +var global environment.GlobalEnvironment
Same as above

2024-03-12 17:35 UTC, Cali0707 commented on test/e2e_source/main_test.go
> +var global environment.GlobalEnvironment
Same as above

2024-03-13 06:20 UTC, NeerajNagure commented on test/e2e/main_test.go
> +var global environment.GlobalEnvironment
for getting a kube client we require a *testing.T type argument while calling testlib.setup().But in the main function we have got *testing.M type argument.So I am stuck here,can I please get some help?

2024-03-13 14:50 UTC, Cali0707 commented on test/e2e/main_test.go
> +var global environment.GlobalEnvironment
Well, what we need is a context object that we can cancel after the test, as well as a kubeclient. If you look at the `testlib.ExportLogs` definition, you'll see that it gets a kubeclient with:
```go
config, err := pkgtest.Flags.GetRESTConfig()
	if err != nil {
	log.Printf("Failed to create REST config: %v\n", err)
	return
}

kubeClient, err := kubernetes.NewForConfig(config)
if err != nil {
	log.Printf("Failed to create kube client: %v\n", err)
	return
}
```
You should be able to reuse this to get a kubeclient. For the context and cancel, that is simpler as you can do something like:
```
ctx, cancel := context.WithCancel(context.Background())

2024-03-13 15:48 UTC, NeerajNagure commented
I have made all the required changes @Cali0707

2024-03-13 16:35 UTC, Cali0707 commented
/ok-to-test

2024-03-13 17:13 UTC, NeerajNagure commented
/retest

2024-03-13 17:20 UTC, NeerajNagure commented
/retest

2024-03-14 14:45 UTC, Cali0707 commented
/retest-required

2024-03-17 16:27 UTC, NeerajNagure commented
@Cali0707 do you want me to do any other changes?

2024-03-18 16:32 UTC, Cali0707 requested changes
This looks great @NeerajNagure ! One last change and then this will be good to merge:

It looks like the imports aren't correctly sorted (look at the lint errors on this PR). The easy way to fix this is to run goimports on your files (article on how to do this in VSCode here: https://hyr.mn/gofmt/, GoLand/Jetbrains here: https://www.jetbrains.com/help/go/integration-with-go-tools.html).

2024-03-19 10:05 UTC, NeerajNagure commented
/retest-required

2024-03-19 14:21 UTC, NeerajNagure commented
/retest-required

2024-03-19 15:15 UTC, Cali0707 approved these changes
/lgtm
/approve

Thanks @NeerajNagure !!

2024-03-19 16:45 UTC, Cali0707 commented
/test reconciler-tests

2024-03-19 18:24 UTC, Cali0707 commented
/test reconciler-tests

2024-03-19 19:47 UTC, Cali0707 commented
/test reconciler-tests

2024-03-20 04:15 UTC, NeerajNagure commented
/test reconciler-tests

2024-03-20 05:52 UTC, merged