added sacura tests to keda test job
knative-extensions/eventing-kafka-broker pull request #3783
Opened 2024-03-24 09:59 UTC by NeerajNagure

Fixes #3711 

## Proposed Changes
added a script in keda-reconciler-tests.sh that will run sacura tests in it

:gift: Added sacura tests in keda job

2024-03-25 17:59 UTC, Cali0707 requested changes
Thanks for starting on this @NeerajNagure ! Just two small changes

2024-03-25 17:59 UTC, Cali0707 commented on test/keda-reconciler-tests.sh
> +go_test_e2e -tags=sacura -timeout=40m ./test/e2e/... || fail_test "E2E sacura tests failed"
Can you verify that this is not in LOCAL_DEVELOPMENT before running these tests? We should probably also still have the `-run=KafkaSource` flag set for these tests.

To check the LOCAL_DEVELOPMENT, see https://github.com/knative-extensions/eventing-kafka-broker/blob/315e260db7a27c0e899d6b2a34eacc8e5a06abf3/test/reconciler-tests.sh#L73-L75

2024-03-26 06:56 UTC, NeerajNagure commented
@Cali0707 I have added the -run=kafkasource flag and also checked whether the environment is LOCAL_DEVELOPMENT or not before running sacura tests

2024-03-26 13:52 UTC, pierDipi commented on test/keda-reconciler-tests.sh
> +go_test_e2e -run=KafkaSource -tags=sacura -timeout=40m ./test/e2e/... || fail_test "E2E sacura tests failed"
```suggestion
	go_test_e2e -run=KafkaSource -tags=sacura -timeout=40m ./test/e2e/... || fail_test "E2E sacura tests failed"
```

2024-03-26 17:09 UTC, NeerajNagure commented
/retest-required

2024-03-26 17:17 UTC, NeerajNagure commented
/test reconciler-tests

2024-03-27 12:20 UTC, Cali0707 approved these changes
/lgtm
/approve

Thanks @NeerajNagure !!

2024-03-27 13:43 UTC, NeerajNagure commented
/test reconciler-tests

2024-03-27 15:01 UTC, NeerajNagure commented
/retest-required

2024-03-27 15:53 UTC, NeerajNagure commented
/retest-required

2024-03-27 17:16 UTC, Cali0707 commented
/test reconciler-tests-namespaced-broker

2024-03-27 18:35 UTC, pierDipi commented
/test reconciler-tests-namespaced-broker

2024-03-28 04:56 UTC, NeerajNagure commented
/retest-required

2024-03-28 06:10 UTC, NeerajNagure commented
/retest-required

2024-03-28 07:49 UTC, merged